sdkversion: "3.5.0"
name: "EmployeeApp"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "4.6"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator5.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.employeeapp"
  BundleURLScheme: "employeeapp"
wp:
  productid: "dec40070-859b-0131-3dc3-001cc0cca218"
symbian:
  uid: "0xece5c190"
android:
  version: "2.1"
extensions:
  - json
  - another-extension
app_type: "rhoelements"
capabilities:
  - non_motorola_device
